#
# uAPI | Разработчие CRAD (vk.com/gagaga2k17 | https://crad.ovh)
# Плагин разработ для сервера BERRYMINE (BERRYMC.RU)
# Продажа/выдача за свой - запрещена.
#

#
# uAPI.reload - Право на перезагрузку конфигурации плагина
# uAPI.join - Право, которое необходимо, для отображения сообщения о входео
#

# Какие функции плагина будут работаь
join: true # Сообщения при входе на сервер.

messages:
  # Сообщение запрета использования команды через консоль.
  console: '&cКоманду можно использовать только от имени игрока.'
  # Сообщение, при перезагрузки конфигурации плагина.
  reload: '&e&luJoin &8▪ &aПлагин перезагружен.'
  # Сообщение, при недостатки прав у игрока.
  perm: '&e&luJoin &8▪ &cНедостаточно прав.'
  # Сообщение, при неверно введенном аргументе.
  usage: '&e&luJoin &8▪ &cВы ввели неверный аргумент.'

join: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &fзашёл на сервер
join1: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &fвлетел на сервер
join2: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &fвлетел на сверхзвуковой скорости
join3: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &fприсоединился к вечеринке
join4: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6залетел на сервер
join5: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6решил нас посетить
join6: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6прилетел к нам на крыльях
join7: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6выходит из тени...
join8: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6нашел время на нас, давайте его поприветствуем
join9: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6был рассекрчен
join10: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
    &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6подключился, надеемся что у него нет коронавируса...
join11: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
  &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6перевернул игру
join12: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
  &a&l⎪ &r%vault_prefix% <player>%vault_suffix% &6всплошил весь округ
join13: 
  # Сообщение, которое будут видеть игроки, при заходе другого игрока | <player> - Заменяется на ник игрока 
  messages: |
  &a
